
package clientsga.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonServiceWS", targetNamespace = "http://service.sga.dss.com.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonServiceWS {


    /**
     * 
     * @return
     *     returns java.util.List<clientsga.ws.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPeople", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.ListPeople")
    @ResponseWrapper(localName = "listPeopleResponse", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.ListPeopleResponse")
    @Action(input = "http://service.sga.dss.com.ar/PersonServiceWS/listPeopleRequest", output = "http://service.sga.dss.com.ar/PersonServiceWS/listPeopleResponse")
    public List<Person> listPeople();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.UpdatePersonResponse")
    @Action(input = "http://service.sga.dss.com.ar/PersonServiceWS/updatePersonRequest", output = "http://service.sga.dss.com.ar/PersonServiceWS/updatePersonResponse")
    public void updatePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.AddPersonResponse")
    @Action(input = "http://service.sga.dss.com.ar/PersonServiceWS/addPersonRequest", output = "http://service.sga.dss.com.ar/PersonServiceWS/addPersonResponse")
    public void addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service.sga.dss.com.ar/", className = "clientsga.ws.DeletePersonResponse")
    @Action(input = "http://service.sga.dss.com.ar/PersonServiceWS/deletePersonRequest", output = "http://service.sga.dss.com.ar/PersonServiceWS/deletePersonResponse")
    public void deletePerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

}
