
package clientws.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SumServiceWSImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8080/SumServiceWSImplService/SumServiceWSImpl?wsdl")
public class SumServiceWSImplService
    extends Service
{

    private final static URL SUMSERVICEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUMSERVICEWSIMPLSERVICE_EXCEPTION;
    private final static QName SUMSERVICEWSIMPLSERVICE_QNAME = new QName("http://beans/", "SumServiceWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SumServiceWSImplService/SumServiceWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUMSERVICEWSIMPLSERVICE_WSDL_LOCATION = url;
        SUMSERVICEWSIMPLSERVICE_EXCEPTION = e;
    }

    public SumServiceWSImplService() {
        super(__getWsdlLocation(), SUMSERVICEWSIMPLSERVICE_QNAME);
    }

    public SumServiceWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUMSERVICEWSIMPLSERVICE_QNAME, features);
    }

    public SumServiceWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SUMSERVICEWSIMPLSERVICE_QNAME);
    }

    public SumServiceWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUMSERVICEWSIMPLSERVICE_QNAME, features);
    }

    public SumServiceWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumServiceWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SumServiceWS
     */
    @WebEndpoint(name = "SumServiceWSImplPort")
    public SumServiceWS getSumServiceWSImplPort() {
        return super.getPort(new QName("http://beans/", "SumServiceWSImplPort"), SumServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SumServiceWS
     */
    @WebEndpoint(name = "SumServiceWSImplPort")
    public SumServiceWS getSumServiceWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "SumServiceWSImplPort"), SumServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUMSERVICEWSIMPLSERVICE_EXCEPTION!= null) {
            throw SUMSERVICEWSIMPLSERVICE_EXCEPTION;
        }
        return SUMSERVICEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
